#!/bin/sh

# Register the icons needed for JBrofuzz and the OWASP menu
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-jbrofuzz/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-jbrofuzz/owasp-wte-jbrofuzz-icon.png owasp-wte-jbrofuzz-icon 

# Create the necessary menu entries
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-jbrofuzz/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-jbrofuzz/owasp-fuzzer.directory \
                         /opt/owasp/tmp/owasp-wte-jbrofuzz/owasp-wte-jbrofuzz.desktop
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-jbrofuzz/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-jbrofuzz/owasp-fuzzer.directory \
                         /opt/owasp/tmp/owasp-wte-jbrofuzz/owasp-wte-jbrofuzz-encoder.desktop


# Cleanup /tmp
rm -rf /opt/owasp/tmp/owasp-wte-jbrofuzz
