#!/bin/bash

LIB="../../scripts"

if [[ ! -d "$LIB" ]]; then
  echo "Cannot file scripts directory."
  echo "  Are you in the root directory of the tool you want to package?"
  exit 1
fi

# Set values needed to build debs and rpms with FPM
TOOLNAME="EDIT" # What tool are you working on?
VERSION="EDIT"  # What version of that tool are you packaging?
# Description of the tool that is being packaged.
DESCRIPT="EDIT"
# Version of the actual deb/rpm is this - if not fixing a packaging bug, then 00, else increment this by 1
ITER="00" 
# What packages are needed to install this on Debian/Ubuntu systems? 
# e.g. --depends "firefox | iceweasel"
DEBDEPENDS=""
# What packages are needed to install this on RedHat/CentOS/Fedora systems? 
# e.g. --depends firefox
RPMDEPENDS=""
# Architechture this packge is built for? Choose from: all, native, i386, amd64
ARCH="EDIT"
# Scripts to run before or after installation.  Once script per option below
# --after-install FILE - A script to be run after package installation
# --before-install FILE - A script to be run before package installation
# e.g. INSTALLSCRIPTS="--before-install scripts/preinst"
INSTALLSCRIPTS=""
# Simlar to INSTALLSCRIPTS but occur when the package is removed.  Options are:
# --after-remove FILE - A script to be run after package removal
# --before-remove FILE - A script to be run before package removal
# e.g. REMOVESCRIPTS="--after-remove scripts/postrm"
REMOVESCRIPTS=""
# Additional .deb or .rpm FPM arguments
# e.g. ADDDEB="--deb-recommends owasp-wte-firefox"
ADDDEB=""
ADDRPM=""

# Call the global build script
source $LIB/make-package

# Check for the packages directory
if [[ ! -d "./packages" ]]; then
  echo "Cannot find packages directory - creating it now."
  mkdir ./packages
fi

# Make sure the package creation worked as expected
COUNT=`ls ./$PACKAGER$SEP* | wc -l`
if [ $COUNT -eq 2 ] 
then
  # Move packages into subdirectory
  mv *.deb ./packages/
  mv *.rpm ./packages/
  echo "Debian and RPM files moved to ./packages/"
elif [ $COUNT -gt 2 ] 
then
  echo "ERROR: Something wonky happened.  It appears that more then just .deb and .rpms were created"
else
  echo "ERROR: Both .deb and .rpm were not created.  Any package files created were left in the current directory."
fi
