#!/bin/sh

# Register the icons needed for Spikeproxy and the OWASP menu
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-spikeproxy/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-spikeproxy/owasp-wte-spikeproxy-icon.png owasp-wte-spikeproxy-icon 

# Create the necessary menu entries
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-spikeproxy/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-spikeproxy/owasp-proxies.directory \
                         /opt/owasp/tmp/owasp-wte-spikeproxy/owasp-wte-spikeproxy.desktop

# Cleanup /opt/owasp/tmp
rm -rf /opt/owasp/tmp/owasp-wte-spikeproxy
