#!/bin/sh

# Register the icons needed for mini-rest and the OWASP menu
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-mini-rest/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-mini-rest/owasp-wte-mini-rest-icon.png owasp-wte-mini-rest-icon 

# Create the necessary menu entries
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-mini-rest/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-mini-rest/owasp-rest.directory \
                         /opt/owasp/tmp/owasp-wte-mini-rest/owasp-wte-mini-rest.desktop

# Cleanup /opt/owasp/tmp
rm -rf /opt/owasp/tmp/owasp-wte-mini-rest
