#!/bin/bash

LIB="../scripts"

if [[ ! -d "$LIB" ]]; then
  echo "Cannot file scripts directory."
  echo "  Are you in the root directory of the tool you want to package?"
  exit 1
fi

# Set values needed to build deb's and rpm's with FPM
TOOLNAME="jerry-curl" # What tool are you working on?
VERSION="1.1"   # What version of that tool are you packaging?
# Description of the tool that is being packaged.
DESCRIPT="jerry-curl is a wrapper for the curl command which adds options from a configuration file and the command line allowing for short repeated curl calls.  Basically, it helps put your long curl commands on a diet.  The result of a jerry-curl command is a union of what is in the configuration file and the command-line options you add to jerry-curl. Of the command-line options, those meant for jerry-curl are processed and those meant for curl are passed through to curl."
# Version of the actual deb/rpm is this - if not fixing a packaging bug, then 00, else increment this by 1
ITER="00" 
# What packages are needed to install this on Debian/Ubuntu systems?
DEBDEPENDS=""
# What packages are needed to install this on RedHat/CentOS/Fedora systems?
RPMDEPENDS=""
# Architechture this packge is built for? Choose from: all, native, i386, amd64
ARCH="amd64"
# Scripts to run before or after installation.  Once script per option below
# --after-install FILE - A script to be run after package installation
# --before-install FILE - A script to be run before package installation
# e.g. INSTALLSCRIPTS="--before-install scripts/prep-for-install"
INSTALLSCRIPTS="--after-install scripts/postinst"
# Simlar to INSTALLSCRIPTS but occur when the package is removed.  Options are:
# --after-remove FILE - A script to be run after package removal
# --before-remove FILE - A script to be run before package removal
REMOVESCRIPTS="--after-remove scripts/postrm"
# Additional .deb or .rpm FPM arguments
ADDDEB=""
ADDRPM=""
# Is this a 64-bit build?
AMD64=true

# Call the global build script
source $LIB/build-from-previous

# Check for the packages directory
if [[ ! -d "./packages" ]]; then
  echo "Cannot find packages directory - creating it now."
  mkdir ./packages
fi

# Make sure the package creation worked as expected
COUNT=`ls ./owasp-wte-* | wc -l`
if [ $COUNT -eq 2 ] 
then
  # Move packages into subdirectory
  mv *.deb ./packages/
  mv *.rpm ./packages/
  echo "Debian and RPM files moved to ./packages/"
else
  echo "ERROR: Both .deb and .rpm were not created.  Package files left if the current directory"
fi
