#!/bin/sh

# Register the icons needed for Webslayer and the OWASP menu
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-webslayer/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-webslayer/owasp-wte-webslayer-icon.png owasp-wte-webslayer-icon 

# Create the necessary menu entries
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-webslayer/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-webslayer/owasp-fuzzer.directory \
                         /opt/owasp/tmp/owasp-wte-webslayer/owasp-wte-webslayer.desktop

# Cleanup /opt/owasp/tmp
rm -rf /opt/owasp/tmp/owasp-wte-webslayer
