#!/bin/sh

# Register the icons needed for skipfish and the OWASP menu
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-skipfish/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-skipfish/owasp-wte-skipfish-icon.png owasp-wte-skipfish-icon 

# Create the necessary menu entries
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-skipfish/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-skipfish/owasp-scanners.directory \
                         /opt/owasp/tmp/owasp-wte-skipfish/owasp-wte-skipfish.desktop

# Cleanup /opt/owasp/tmp
rm -rf /opt/owasp/tmp/owasp-wte-skipfish
