#!/bin/sh

# Register the icons needed for Dirbuster and the OWASP menu
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-dirbuster/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-dirbuster/owasp-wte-dirbuster-icon.png owasp-wte-dirbuster-icon 

# Create the necessary menu entries
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-dirbuster/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-dirbuster/owasp-fuzzer.directory \
                         /opt/owasp/tmp/owasp-wte-dirbuster/owasp-wte-dirbuster.desktop

# Cleanup /tmp
rm -rf /opt/owasp/tmp/owasp-wte-dirbuster
