#!/bin/sh

# Register the icons needed for Fierce Domain Scanner and the OWASP menu
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-fierce/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-fierce/owasp-wte-fierce-icon.png owasp-wte-fierce-icon 

# Create the necessary menu entries
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-fierce/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-fierce/owasp-recon.directory \
                         /opt/owasp/tmp/owasp-wte-fierce/owasp-wte-fierce.desktop

# Cleanup /tmp
rm -rf /opt/owasp/tmp/owasp-wte-fierce
