#!/bin/sh

# Register the icons needed for jq and the OWASP menu
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-jq/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-jq/owasp-wte-jq-icon.png owasp-wte-jq-icon 

# Create the necessary menu entries
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-jq/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-jq/owasp-rest.directory \
                         /opt/owasp/tmp/owasp-wte-jq/owasp-wte-jq.desktop

# Cleanup /opt/owasp/tmp
rm -rf /opt/owasp/tmp/owasp-wte-jq
