#!/bin/sh

# Register the icons needed for Gruyere and the OWASP menu
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-gruyere/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-gruyere/owasp-wte-gruyere-icon.png owasp-wte-gruyere-icon 

# Create the necessary menu entries
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-gruyere/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-gruyere/owasp-wte-gruyere.desktop

# Cleanup /tmp
rm -rf /opt/owasp/tmp/owasp-wte-gruyere
