#!/bin/sh

# Register the icons needed for Firefox WTE Style and the OWASP menu
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-firefox/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-firefox/owasp-wte-firefox-icon.png owasp-wte-firefox-icon 

# Create the necessary menu entries
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-firefox/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-firefox/owasp-wte-firefox.desktop

# Cleanup /opt/owasp/tmp
rm -rf /opt/owasp/tmp/owasp-wte-firefox
