#!/bin/sh

# Register the icons needed for WebGoat and the OWASP menu
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-webgoat/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /opt/owasp/tmp/owasp-wte-webgoat/owasp-wte-webgoat-icon.png owasp-wte-webgoat-icon 

# Create the necessary menu entries
# Start WebGoat
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-webgoat/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-webgoat/owasp-wte-webgoat-start.desktop
# Stop WebGoat
xdg-desktop-menu install /opt/owasp/tmp/owasp-wte-webgoat/owasp-owasp.directory \
                         /opt/owasp/tmp/owasp-wte-webgoat/owasp-wte-webgoat-stop.desktop

# Cleanup /opt/owasp/tmp
rm -rf /opt/owasp/tmp/owasp-wte-webgoat
